language: python
python:
- '2.6'
- '2.7'
install:
- python setup.py install
- pip freeze
- pip install pep8
script:
- pep8 qcloud_cos --max-line-length=140
- nosetests
deploy:
  provider: pypi
  user: liuchang0812
  password:
    secure: B+yhh1dUtQzNz5Yozp9NVORoUybyq0v0wrpkOURIgbv1H9lG+kLmkTD+Gtc3cfhAIzq9VXJZtcSuh2uKuIIP+6Lo/UKMA91eCJR345WGW7HZsz/erI/y7Zh0ART6DL2ZAC1k+XstrmRTgjdD7kq7JwD2CtJRCJl74WjS5YhzDXgRWNLmw22HL4eK0kPubN+2VdoJNCQY2Rd262TZ/YkO3K+Vd3l6EttWr7uKCafl68AkqUYs0nujTrCdUVezIxIq5qxI5FJYhB6yBl36oI1yCaKMeHlmZ8jw8rt15wqMV3es4ggrQKhvVBkoatAY2HnZcHgutitp3PbVmP/5uRabBA/9kTASPYW0SEi1G8itfk7mNqLAC4lFuw2bq03tbOPnA/j6q1B46HXAk5adgyG+k46y7xRJIcXTo29h1F01hRekT+J431SPR3/qRPiONQ3NpkD5vfBSVvuz0q1Kt++HgE4q/6ej3am0/1a7kVL87WmmH+qzmDPPNOo0BiTxJZ/X2bgmid5yF4EqNuoAde6StKnkqYmvZBsd1noE6EwcNhU1S1Wr/ecTtscfHgN0b/eaLIep9OL6ZzffuUjvZwIpzf7xIhuYluNg2XtaunfVEeVRqU+SKWQ9AD+3ZZqpr04Cbbtu+j7SNQw8y9hkJQxdib+K/xK/3AHpZ1YWL+WTwtA=
  on:
    tags: true
    branch: master
